name: Push-to-EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v3

    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      env:
        key: ${{secrets.EC2_SSH_KEY}}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: "./"
        host: ${{secrets.REMOTE_HOST}}
        username: ${{secrets.REMOTE_USER}}
        TARGET: "/home/ec2-user/node"
        script: |
            cd ~/node
            yarn/npm install
            yarn/npm build
            yarn/npm i serve
            serve -p 3000 build/
        EXCLUDE: "/dist/, /node_modules/, **.env, rebuild_app.sh, watcher.sh"